---
- name: Manage GNS3 devices
  hosts: sw1,sw2,sw3
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 120

    - name: Verification
      ios_command:
        provider: "{{ provider }}"
        commands:
          - ping 192.168.11.1
          - ping 192.168.11.2
          - ping 192.168.13.3
          - ping 192.168.13.4
      register: if_data
    - debug:
        var: if_data['stdout_lines'][0]

