---
- name: Manage GNS3 devices
  hosts: routers,switches
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 60

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - hostname {{ inventory_hostname }}
        save_when: modified

    - name: Verification
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show run | in hostname
      register: if_data
    - debug:
        var: if_data['stdout_lines'][0]

