---
- name: Manage GNS3 devices
  hosts: sw4,sw5,sw6
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 60

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface gi0/0
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
          - interface gi0/1
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
          - interface gi1/0
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
        save_when: modified
      when: inventory_hostname == 'sw4'

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface gi0/0
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
          - interface gi0/1
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
          - interface gi1/1
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
        save_when: modified
      when: inventory_hostname == 'sw5'

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface gi1/0
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
          - interface gi1/1
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - speed auto
          - duplex auto
        save_when: modified
      when: inventory_hostname == 'sw6'
