---
- name: Manage GNS3 devices
  hosts: routers, switches
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 60

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - service timestamps debug datetime msec localtime
          - service timestamps log datetime msec localtime
          - service password-encryption
          - service tcp-keepalives-in
          - service tcp-keepalives-out
          - service sequence-numbers
        save_when: modified
