---
- name: Manage GNS3 devices
  hosts: sw1,sw2,sw3
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 60

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface fa1/0
          - spanning-tree vlan 1 cost 1
          - interface fa1/1
          - spanning-tree vlan 1 cost 1
          - interface fa1/2
          - spanning-tree vlan 1 cost 1
        save_when: modified
      when: inventory_hostname == 'sw1'

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface fa1/0
          - spanning-tree vlan 1 cost 1
          - interface fa1/1
          - spanning-tree vlan 1 cost 1
          - interface fa1/3
          - spanning-tree vlan 1 cost 1
        save_when: modified
      when: inventory_hostname == 'sw2'

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface fa1/2
          - spanning-tree vlan 1 cost 1000
          - interface fa1/3
          - spanning-tree vlan 1 cost 1000
        save_when: modified
      when: inventory_hostname == 'sw3'

