---
- name: Manage GNS3 devices
  hosts: switches
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 120

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - enable secret ansible
          - username ansible pri 15 sec ansible
          - username admin pri 15 sec admin
        save_when: modified

