---
- name: Manage GNS3 devices
  hosts: switches
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 120

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface range fa1/10 - 11
          - switchport access vlan 11
          - switchport mode access
          - description PC
          - interface range fa1/12 - 13
          - switchport access vlan 13
          - switchport mode access
          - description PC
          - interface range fa1/2 - 3
          - switchport trunk encap dot1q
          - switchport mode trunk
          - description UPLINK
        save_when: modified
      when: inventory_hostname == 'sw3'

