---
- name: Manage GNS3 devices
  hosts: switches
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 120

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface vlan 11
          - no shutdown
          - ip address 192.168.11.254 255.255.255.0
          - description VLAN 11 - Sales
        save_when: modified
      when: inventory_hostname == 'sw1'

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface vlan 13
          - no shutdown
          - ip address 192.168.13.254 255.255.255.0
          - description VLAN 13 - Marketing
        save_when: modified
      when: inventory_hostname == 'sw1'

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface vlan 15
          - no shutdown
          - ip address 192.168.15.254 255.255.255.0
          - description VLAN 15 - Accounting
        save_when: modified
      when: inventory_hostname == 'sw5'

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - interface vlan 17
          - no shutdown
          - ip address 192.168.17.254 255.255.255.0
          - description VLAN 17 - Engineering
        save_when: modified
      when: inventory_hostname == 'sw5'

    - name: Verification
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show ip int bri | in Vlan
      register: if_data
    - debug:
        var: if_data['stdout_lines'][0]

