---
- name: Manage GNS3 devices
  hosts: sw1
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 60

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - ip domain-name domain.local
          - crypto key generate rsa modulus 1024
          - ip ssh version 2
          - aaa new-model
          - aaa authentication login default local
          - username adrian privilege 15 secret adrian
          - username nimax privilege 15 secret nimax
          - line vty 0 15
          - login authentication default
          - transport input ssh telnet
        save_when: modified

