---
- name: Manage GNS3 devices
  hosts: switches
  gather_facts: false
  connection: local
 
  tasks:
    - name: Obtain Login Information
      include_vars: secrets.yml

    - name: Define Provider
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
          timeout: 60

    - name: Configuration
      ios_config:
        provider: "{{ provider }}"
        lines:
          - line vty 0 15
          - privilege level 15
          - password ansible
          - session-timeout 1
          - exec-timeout 1 0
          - transport input all
          - logging synchronous
          - username ansible pri 15 sec ansible
          - username admin pri 15 sec admin
          - line console 0
          - logging synchronous
          - password ansible
          - exec-timeout 1 0
        save_when: modified

